### ISSUE TITLE
Kurslar pagega otmadi error

### ISSUE THREAD

**Issue by eugene0928** [definem/najot-talim#1]
https://github.com/definem/najot-talim/blob/bbfa69da3cb4f5e3ea1499b5d78ffbdf9f8c8849/index.html#LL29C29-L29C29

linkda corses.html ga yuborilgan lekin unaqa file yoq. manimcha verselda qayta deploy qlin

**Comment by definem** [comment]
assalamu alaykum. xo'p bo'ladi ustoz. working on it 🫡

**Comment by definem** [comment]
> 

I tried to understand but I couldn't. What should I do?

**Comment by eugene0928** [comment]
![image](https://github.com/definem/najot-talim/assets/91713813/f74096c0-14df-4332-99b6-35ac1bc291c8)

In your blog.html file u gave a link to courses like in the pic above, but u don't have courses.html file. U have `cousees.html`. That's why change that url to `cousees.html`

**Comment by definem** [comment]
> ![image](https://user-images.githubusercontent.com/91713813/241125261-f74096c0-14df-4332-99b6-35ac1bc291c8.png)
> 
> In your blog.html file u gave a link to courses like in the pic above, but u don't have courses.html file. U have `cousees.html`. That's why change that url to `cousees.html`


Got it thanks.
